language: java
jdk:
  - openjdk11

notifications:
  email: false

script:
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:resources/3rdparty/glpk/lib/jni
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dmaven.test.redirectTestOutputToFile -Dmatsim.preferLocalDtds=true
  - mvn test -B -Dmaven.test.redirectTestOutputToFile -Dmatsim.preferLocalDtds=true
